language: elixir

sudo: false

elixir:
  - 1.2
  - 1.3
  - 1.4

otp_release:
  - 17
  - 18
  - 19

env: MIX_ENV=test

script:
  - mix coveralls.travis
  - mix credo --strict

notifications:
  email: false
