
language: elixir

sudo: false

elixir:
  - 1.1.0
  - 1.2.6
  - 1.3.1

otp_release:
  - 17.4
  - 18.1

env: MIX_ENV=test

script:
  - mix credo --strict
  - mix coveralls.travis

notifications:
  email: false
